name: Build and Release

on:
  push:
    tags:
      - "v*"   # 当推送 tag，如 v1.0.0 时触发
  workflow_dispatch:   # 手动触发

jobs:
  build:
    name: Build binaries on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build binary
        run: |
          pyinstaller --onefile main.py
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-x64-binary
          path: dist/main*

  build-arm:
    name: Build Linux ARM64 binary
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Build ARM64 binary with Docker
        run: |
          docker run --rm --platform linux/arm64 -v ${{ github.workspace }}:/src -w /src python:3.9 bash -c "
            pip install --upgrade pip &&
            pip install -r requirements.txt pyinstaller &&
            pyinstaller --onefile main.py
          "
      - name: Upload ARM64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm64-binary
          path: dist/main*

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build, build-arm]
    steps:
      - name: Download x64 Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-latest-x64-binary
          path: dist/linux

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-latest-x64-binary
          path: dist/windows

      - name: Download ARM64 Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-arm64-binary
          path: dist/linux-arm64

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/linux/*
            dist/linux-arm64/*
            dist/windows/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
