name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    name: Build binaries on ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        arch: [x64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build binary
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            pyinstaller --onefile main.py --name main-${{ matrix.os }}-${{ matrix.arch }}
          else
            pyinstaller --onefile main.py --name main-${{ matrix.os }}-${{ matrix.arch }}.exe
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}-binary
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux x64
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-latest-x64-binary
          path: dist/linux/x64

      - name: Download Linux ARM
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-latest-arm64-binary
          path: dist/linux/arm64

      - name: Download Windows x64
        uses: actions/download-artifact@v4
        with:
          name: windows-latest-x64-binary
          path: dist/windows/x64

      - name: Download Windows ARM
        uses: actions/download-artifact@v4
        with:
          name: windows-latest-arm64-binary
          path: dist/windows/arm64

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/linux/x64/*
            dist/linux/arm64/*
            dist/windows/x64/*
            dist/windows/arm64/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
