name: Build and Release

on:
  push:
    tags:
      - "v*"   # 当推送 tag，如 v1.0.0 时触发
  workflow_dispatch:   # 也可以手动触发

jobs:
  build:
    name: Build binaries on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build binary
        run: |
          pyinstaller --onefile main.py
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-binary
          path: dist/main*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-latest-binary
          path: dist/ubuntu
      - uses: actions/download-artifact@v4
        with:
          name: windows-latest-binary
          path: dist/windows
      - uses: actions/download-artifact@v4
        with:
          name: macos-latest-binary
          path: dist/macos

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/ubuntu/*
            dist/windows/*
            dist/macos/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
