name: Build and Release

on:
  push:
    tags:
      - "v*"   # 推送 tag 时触发
  workflow_dispatch:   # 手动触发

jobs:
  build-x64:
    name: Build x64 binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build binary
        run: |
          pyinstaller --onefile main.py
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-x64-binary
          path: dist/main*

  build-arm:
    name: Build ARM Linux binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build ARM binary with Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/src -w /src arm64v8/python:3.9 bash -c "
          pip install --upgrade pip &&
          pip install -r requirements.txt pyinstaller &&
          pyinstaller --onefile main.py
          "
      - name: Upload ARM artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm64-binary
          path: dist/main*

  release:
    name: Create GitHub Release
    needs: [build-x64, build-arm]
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux x64 artifact
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-latest-x64-binary
          path: dist/linux
      - name: Download Windows x64 artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-latest-x64-binary
          path: dist/windows
      - name: Download ARM Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-arm64-binary
          path: dist/linux-arm

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/linux/*
            dist/windows/*
            dist/linux-arm/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
